spring.application.name=backendClaude
spring.datasource.url=jdbc:mysql://localhost:3306/acainfo?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=7leDeli8
spring.jpa.show-sql=true